CREATE TABLE IF NOT EXISTS recent_updates (
id VARCHAR(64) NOT NULL,
title VARCHAR(255) NOT NULL,
num VARCHAR(255) NOT NULL,
updateDate BIGINT NOT NULL,
icon VARCHAR(255) NOT NULL,
url VARCHAR(255) NOT NULL,
createdAt BIGINT NOT NULL,
updatedAt BIGINT NOT NULL,
version BIGINT NOT NULL,
PRIMARY KEY(id)
) ENGINE=InnoDB CHARSET=utf8;